# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tip.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_tip(object):
    def setupUi(self, tip):
        
        current_dir = os.path.dirname(__file__)
        self.img_file = os.path.join(current_dir, "background.png")

        tip.setObjectName("tip")
        tip.setEnabled(True)
        tip.resize(1000, 600)
        tip.setLayoutDirection(QtCore.Qt.LeftToRight)
        tip.setStyleSheet("background-color: rgb(255, 241, 171);\n"
"")
        self.textBrowser = QtWidgets.QTextBrowser(tip)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(200, 100, 600, 250))
        self.textBrowser.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(tip)
        self.pushButton.setGeometry(QtCore.QRect(400, 370, 211, 50))
        font = QtGui.QFont()
        font.setFamily("田氏颜体大字库")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"田氏颜体大字库\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(tip)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 440, 211, 50))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"田氏颜体大字库\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(tip)
        self.label.setGeometry(QtCore.QRect(0, 0, 1001, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.img_file))
        self.label.setObjectName("label")
        self.label.raise_()
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(tip)
        QtCore.QMetaObject.connectSlotsByName(tip)

    def retranslateUi(self, tip):
        _translate = QtCore.QCoreApplication.translate
        tip.setWindowTitle(_translate("tip", "手势识别小游戏"))
        self.textBrowser.setHtml(_translate("tip", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'田氏颜体大字库\',\'Courier New\',\'monospace\'; font-size:20pt; font-weight:600; color:#000000;\">    我们会给出20张图片，根据所给的手势图片请在摄像头前做出相应的手势，每张图片会有7秒的停留时间。根据你所做的手势我们会计算出匹配得分并汇总。你准备好了吗？</span></p></body></html>"))
        self.pushButton.setText(_translate("tip", "准备好了，开始游戏"))
        self.pushButton_2.setText(_translate("tip", "还没做好准备，再等等"))
